language: cpp

install:
  - pip install --user conan cmake
  - sudo add-apt-repository ppa:nnstreamer/ppa
  - sudo apt-get update
#  - echo "deb http://cz.archive.ubuntu.com/ubuntu eoan main universe" | sudo tee -a  /etc/apt/sources.list

jobs:
  include:
#    - os: osx
#      compiler: gcc
#      osx_image: xcode11.2    # includes gcc-9 by default
#      env:
#        # Conan is at: ${HOME}/Library/Python/2.7/bin: we need this in the path
#        - PATH="${HOME}/Library/Python/2.7/bin:${PATH}"
#        - GCC_VER="9"
#        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
#      after_script:
#        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-${GCC_VER}
#    - os: osx
#      compiler: clang
#      osx_image: xcode11.2
#      env:
#        - PATH="${HOME}/Library/Python/2.7/bin:${PATH}"
#        - MATRIX_EVAL=""
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # I couldn't get ${GCC_VER} in here successfully
            - gcc-9
            - g++-9
            - doxygen
            - libtbb-dev
      after_script:
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-${GCC_VER}
    - os: linux
      dist: bionic
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      addons:
        apt:
          packages:
            - clang-9
            - doxygen
            - libtbb-dev


before_script:
  - eval "${MATRIX_EVAL}"

script:
#  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE .
  - cmake --build . -- -j2
  - ctest -j2



