function(enable_doxygen)
    option(ENABLE_DOXYGEN "Enable doxygen doc builds of source" ON)
    if (ENABLE_DOXYGEN)
        set(DOXYGEN_GENERATE_HTML YES)
        set(DOXYGEN_EXTRACT_ALL NO)
        set(DOXYGEN_EXCLUDE_PATTERNS "*/venv/*" "*/build/*" "*/cmake-build*")
        set(DOXYGEN_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/docs)
        set(DOXYGEN_DOXYGEN_USE_MATHJAX YES)
        set(DOXYGEN_DOXYGEN_USE_MATHJAX YES)
        set(DOXYGEN_JAVADOC_AUTOBRIEF YES)
        set(DOXYGEN_EXTRACT_PRIVATE NO)
        set(DOXYGEN_EXTRACT_PRIV_VIRTUAL YES)
        set(DOXYGEN_EXTRACT_PACKAGE YES)
        set(DOXYGEN_EXTRACT_STATIC YES)
        set(DOXYGEN_EXTRACT_LOCAL_CLASSES YES)
        set(DOXYGEN_EXTRACT_LOCAL_METHODS YES)
        set(DOXYGEN_EXTRACT_ANON_NSPACES YES)
        set(DOXYGEN_STRIP_FROM_INC_PATH src)
        find_package(Doxygen OPTIONAL_COMPONENTS dot)
        if (DOXYGEN_HAVE_DOT)
            set(DOXYGEN_CALLER_GRAPH YES)
            set(DOXYGEN_CALL_GRAPH YES)
        endif ()
        if (DOXYGEN_FOUND)
            use_doxygen_awesome_css()
            doxygen_add_docs(doxygen-docs ${PROJECT_SOURCE_DIR})
            message("Using doxygen version ${DOXYGEN_VERSION}")
        endif ()
    endif ()
endfunction()

macro(use_doxygen_awesome_css)
    include(FetchContent)
    FetchContent_Declare(doxygen-awesome-css
            GIT_REPOSITORY
            https://github.com/jothepro/doxygen-awesome-css.git
            GIT_TAG
            v2.1.0
            )
    FetchContent_MakeAvailable(doxygen-awesome-css)
    set(DOXYGEN_GENERATE_TREEVIEW YES)
    set(DOXYGEN_DISABLE_INDEX NO)
    set(DOXYGEN_GFULL_SIDEBAR NO)
    set(DOXYGEN_HAVE_DOT YES)
    set(DOXYGEN_DOT_IMAGE_FORMAT svg)
    set(DOXYGEN_DOT_TRANSPARENT YES)
    set(DOXYGEN_HTML_EXTRA_STYLESHEET ${doxygen-awesome-css_SOURCE_DIR}/doxygen-awesome.css)
endmacro()
