function(enable_doxygen)
  option(ENABLE_DOXYGEN "Enable doxygen doc builds of source" ON)
  if(ENABLE_DOXYGEN)
    set(DOXYGEN_EXTRACT_ALL YES)
    set(DOXYGEN_EXCLUDE_PATTERNS "*/venv/*" "*/build/*" "*/cmake-build*")
    set(DOXYGEN_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/build)
    find_package(Doxygen OPTIONAL_COMPONENTS dot)
    if (DOXYGEN_HAVE_DOT)
      set(DOXYGEN_CALLER_GRAPH YES)
      set(DOXYGEN_CALL_GRAPH YES)
    endif()
    doxygen_add_docs(doxygen-docs ${PROJECT_SOURCE_DIR})
    message("Using doxygen")
  endif()
endfunction()
